#!/usr/bin/env ruby

$LOAD_PATH.unshift( File.join(File.dirname(__FILE__),'lib') );

require 'rubygems'
require 'workhorse'
require 'require_all'
begin
  require_rel 'lib/workhorse/actions' 
rescue Exception 
  # Report on error encountered and what handlers actually loaded, then try and continue
  $stderr.puts $!
  $stderr.puts WH::Actions::handlers.inspect
end

trap("INT") { WH.interrupted = true }
trap("TERM") { WH.interrupted = true }

WH.run
WH.terminate