#!/bin/sh
#
#

# PROVIDE: workhorse
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable workhorse:
# workhorse_enable (bool):       Set to "NO" by default.
#                                 		Set it to "YES" to enable workhorse
# workhorse_pidfile (path):      Set to "/var/run/workhorse.pid" by default

. /etc/rc.subr

name="workhorse"
rcvar=`set_rcvar`

load_rc_config $name

: ${workhorse_enable="NO"}
: ${workhorse_pidfile="/var/run/workhorse.pid"}

command="/usr/local/workhorse/sbin/workhorse"
pidfile=${workhorse_pidfile}

procname="workhorse"
run_rc_command "$1"
