users:
    staff_csolve_net:
        dbuttineau:
            allowed: all
        jlock:
            allowed: all
        crogers:
            allowed: limited
            handlers:
                system:
                    allowed: limited
                    commands:
                        uptime: allowed
                worker:
                    allowed: none

muc_handles:
    conference_staff_csolve_net:
        derek: dbuttineau@staff.csolve.net
        dbuttineau: dbuttineau@staff.csolve.net
        jlock: jlock@staff.csolve.net
        crogers: crogers@staff.csolve.net