#!/bin/bash
#
# Init file for Workhorse Daemon
#
# chkconfig: 2345 55 25
# description: Workhorse Daemon
#
# processname: workhorse
# config: /usr/local/workhorse/config
# pidfile: /var/run/workhorse.pid

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="workhorse"
WORKHORSE=/usr/local/workhorse/sbin/workhorse
PID_FILE=/var/run/workhorse.pid

start()
{
	echo -n $"Starting $prog:"
	initlog -c "$WORKHORSE" && success || failure	
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/workhorse
	echo
}

stop()
{
	echo -n $"Stopping $prog:"
	if [ -n "`pidfileofproc $WORKHORSE`" ] ; then
	    killproc $WORKHORSE
	else
	    failure $"Stopping $prog"
	fi
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/workhorse
	echo
}

reload()
{
	echo -n $"Reloading $prog:"
	if [ -n "`pidfileofproc $WORKHORSE`" ] ; then
	    killproc $WORKHORSE -HUP
	else
	    failure $"Reloading $prog"
	fi
	RETVAL=$?
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		reload
		;;
	condrestart)
		if [ -f /var/lock/subsys/workhorse ] ; then
			do_restart_sanity_check
			if [ "$RETVAL" = 0 ] ; then
				stop
				# avoid race
				sleep 3
				start
			fi
		fi
		;;
	status)
		status $WORKHORSE
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
		RETVAL=1
esac
exit $RETVAL